= Game from Scratch
Melody Henrich

== What?
This repository is part of a project to build a game (and an engine) from scratch.

== Why?
This project is mostly for educational purposes,
though eventually a game will be made as a result of the work done here.

== Who/Where/When?
This project was started by Melody Henrich at Northeastern University in 2023.
This will be a long-term endeavor, spanning multiple months if not years.

== How?

> How do I contribute?

Start by writing a response to the https://github.com/mixolydianmel/Game-from-Scratch/discussions/2#discussion-5453681[Developer Requests] thread in our Discussions area.

> How do I run the project (for users)?

_Release info WIP_

> How do I run the project (for developers)?

First, download and install https://cmake.org/download/[CMake].
CMake should be available in your package manager of choice, if you are using one.

=== Windows

1. Clone the project locally and `cd` into it

....
> git clone https://github.com/mixolydianmel/Game-from-Scratch.git GFS
> cd GFS
....

2. Run the included `build.bat` file

....
> build.bat
....

3. The newly created `build` directory in the root of the project contains the executable

....
> cd build
> GameFromScratch.exe
....

=== Linux / macOS

1. Clone the project locally and `cd` into it

....
$ git clone https://github.com/mixolydianmel/Game-from-Scratch.git GFS
$ cd GFS
....

2. Run the included `build.sh` file

....
$ chmod +x build.sh
$ ./build.sh
....

3. The newly created `build` directory in the root of the project contains the executable

....
$ cd build
$ ./GameFromScratch
....
