= Game from Scratch
Melody Henrich

== What?
This repository is part of a project to build a game (and an engine) from scratch.

== Why?
This project is mostly for educational purposes,
though eventually a game will be made as a result of the work done here.

== Who/Where/When?
This project was started by Melody Henrich at Northeastern University in 2023.
This will be a long-term endeavor, spanning multiple months if not years.

== How?

> How do I contribute?

Start by writing a response to the https://github.com/mixolydianmel/Game-from-Scratch/discussions/2#discussion-5453681[Developer Requests] thread in our Discussions area.

'''

> How do I run the project (for users)?

_Release info WIP_

'''

> How do I run the project (for developers)?

First, download and install https://cmake.org/download/[CMake].
CMake should be available in your package manager of choice, if you are using one.

Then, downoad and install https://glew.sourceforge.net/[GLEW].
There are instructions on the page if you need them.

Next, clone the repo to your local machine.
....
$ git clone https://github.com/mixolydianmel/Game-from-Scratch.git -b development --recursive
....

From there, building the project is accomplished by running the build script for your platform
(build.sh for Unix systems, build.bat for Windows).
After running, there should be a `build` directory created, which will contain the `gfs` executable.

NOTE: The build output directory can be changed by modifying the exported `BUILD_DIR` varibale in whichever script you are using.

On Windows, you may have to open a Visual Studio project from the `build` directory and build using that.
The executable should be in the same location.
